apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "ecommerce-service-carts"
spec:
  hosts:
  - "*"
  gateways:
  - "ecommerce-gateway"
  http:
  - match:
    - uri:
        prefix: /carts
    route:
    - destination:
        host: "shopping-cart"
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "ecommerce-service-analytics"
spec:
  hosts:
  - "*"
  gateways:
  - "ecommerce-gateway"
  http:
  - match:
    - uri:
        prefix: /analytics
    route:
    - destination:
        host: "shopping-cart-analytics"
        subset: v1