apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "shopping-cart-route-default"
spec:
  hosts:
  - "shopping-cart"
  gateways:
  - "ecommerce-gateway"
  http:
  - route:
    - destination:
        host: "shopping-cart"
        subset: v1