apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: jaeger-http
    port: 80
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
  sessionAffinity: None
  type: LoadBalancer